### ISSUE TITLE
Suggestion: more in-depth discussion of portfolio items

### ISSUE THREAD

**Issue by tteltrab** [mr-attack/nicolascaceres.com#2]
I love the minimalism, but I think that the images/brief overview aren't descriptive enough on-hover/when you go to the app. I think you should find a way to incorporate a link to the github repo. I understand you're trying to keep it minimal, so having a descriptive readme might be a good alternative to bloating your site with descriptions.

![image](https://cloud.githubusercontent.com/assets/1487463/22172095/a0547a98-df6c-11e6-9a0e-b8fc9958601c.png)

E.g., from here, if I click this and then go to your app, for all I know that could be a static site for my location (obviously unlikely, but to be sure I have to look at your source, which is a lot of work for someone trying to decide if they want to give you an interview). 

Since there's no description on your portfolio site or on the project itself (which could be fine), I'd suggest you link to the github and beef up the README (you should provide screenshots in your readme, a more in-depth description of the project/its purpose, a link to the live app, and some description of your approach/tech used). What you have right now doesn't help people who are looking at your portfolio trying to understand as quickly as possible what your deal is.

![image](https://cloud.githubusercontent.com/assets/1487463/22172117/1f3e7b56-df6d-11e6-8964-780d73e554b9.png)
But yeah, ^ will need some updates.

**Comment by mr-attack** [comment]
Readmes updated and new mobile layout to account for no hover state available
