### ISSUE TITLE
Suggestion: Contact enhancement

### ISSUE THREAD

**Issue by tteltrab** [mr-attack/nicolascaceres.com#3]
I'm torn, but I think this might be a bit _too_ minimal, to the point of being amatuer. At the very least,  the clickable links could use more of a hover state and need a larger hitbox (especially for mobile devices - hard to click one or the other with your thumb). Maybe an icon for quick visual identification of the different contact methods, or something of the like.

![image](https://cloud.githubusercontent.com/assets/1487463/22172160/22ac7652-df6e-11e6-94c8-e1834857eaf1.png)

**Comment by mr-attack** [comment]
Added underline on hover and icons
